export const REQUEST_BANNER_STAGE = "REQUEST_BANNER_STAGE";

export const REQUEST_BANNER_PAGE = "REQUEST_BANNER_PAGE";
export const SHOW_BANNER_LIST_SORTING = "SHOW_BANNER_LIST_SORTING";
export const SEARCH_BANNER_LIST = "SEARCH_BANNER_LIST";

export const REQUEST_BANNER = "REQUEST_BANNER";
export const REQUEST_BANNER_SUCCESS = "REQUEST_BANNER_SUCCESS";
export const REQUEST_BANNER_FAIL = "REQUEST_BANNER_FAIL";

export const ADD_BANNER = "ADD_BANNER";
export const ADD_BANNER_SUCCESS = "ADD_BANNER_SUCCESS";
export const ADD_BANNER_FAIL = "ADD_BANNER_FAIL";

export const EDITING_BANNER = "EDITING_BANNER";
export const EDIT_SAVING_BANNER = "EDIT_SAVING_BANNER";

export const UPDATE_BANNER = "UPDATE_BANNER";
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS";
export const UPDATE_BANNER_FAIL = "UPDATE_BANNER_FAIL";

export const BUNCH_DELETE_BANNER = "BUNCH_DELETE_BANNER";
export const DELETE_BANNER = "DELETE_BANNER";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_FAIL = "DELETE_BANNER_FAIL";

export const GET_BANNER_REQUEST = "GET_BANNER_REQUEST";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const BANNER_RESPONSE = "BANNER_RESPONSE";
export const GET_BANNER_FAIL = "GET_BANNER_FAIL";
export const BANNER_CATCHERROR = "BANNER_CATCHERROR";
export const BANNER_RESET = "BANNER_RESET";
export const GET_SELECTED_BANNER_SUCCESS = "GET_SELECTED_BANNER_SUCCESS"
export const UPDATE_SELECTED_BANNER_SUCCESS = "UPDATE_SELECTED_BANNER_SUCCESS"
export const DELETED_SELECTED_BANNER_SUCCESS = "DELETED_SELECTED_BANNER_SUCCESS"

export const REQUEST_POPULAR_BANNER = "REQUEST_POPULAR_BANNER";
export const REQUEST_POPULAR_BANNER_SUCCESS = "REQUEST_POPULAR_BANNER_SUCCESS";
export const REQUEST_POPULAR_BANNER_FAIL = "REQUEST_POPULAR_BANNER_FAIL";

export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const SET_BANNER_PROPERTY = "SET_BANNER_PROPERTY";
export const CANCEL_EDITING_BANNER = "CANCEL_EDITING_BANNER";

export const SET_SHOW_URL = "SET_SHOW_URL";


