export const REQUEST_PARENT_CLASS = "REQUEST_PARENT_CLASS";
export const REQUEST_CLASS_SUCCESS = "REQUEST_CLASS_SUCCESS";
export const REQUEST_CLASS_FAIL = "REQUEST_CLASS_FAIL";

export const SET_PARENT_CLASS_OPTIONS = "SET_PARENT_CLASS_OPTIONS";

export const REQUEST_CLASS = "REQUEST_CLASS";
export const REQUEST_CLASS_PAGE = "REQUEST_CLASS_PAGE";
export const SHOW_CLASS_LIST_SORTING = "SHOW_CLASS_LIST_SORTING";

export const REQUEST_CLASS_LIST = "REQUEST_CLASS_LIST";
export const REQUEST_CLASS_LIST_SUCCESS = "REQUEST_CLASS_LIST_SUCCESS";
export const REQUEST_CLASS_LIST_FAIL = "REQUEST_CLASS_LIST_FAIL";

// export const REQUEST_All_CLASS_LIST = "REQUEST_All_CLASS_LIST";
// export const REQUEST_ALL_CLASS_LIST_SUCCESS = "REQUEST_ALL_CLASS_LIST_SUCCESS";
// export const REQUEST_ALL_CLASS_LIST_FAIL = "REQUEST_ALL_CLASS_LIST_FAIL";

export const ADD_CLASS = "ADD_CLASS";
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const ADD_CLASS_FAIL = "ADD_CLASS_FAIL";

export const EDITING_CLASS = "EDITING_CLASS";
export const EDIT_SAVING_CLASS = "EDIT_SAVING_CLASS";
export const EDIT_CLASS_SUCCESS = "EDIT_CLASS_SUCCESS";
export const EDIT_CLASS_FAIL = "EDIT_CLASS_FAIL";

export const BUNCH_DELETE_CLASS = "BUNCH_DELETE_CLASS";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_FAIL = "DELETE_CLASS_FAIL";

export const GET_CLASS_REQUEST = "GET_CLASS_REQUEST";
export const GET_CLASS_SUCCESS = "GET_CLASS_SUCCESS";
export const CLASS_RESPONSE = "CLASS_RESPONSE";
export const GET_CLASS_FAIL = "GET_CLASS_FAIL";
export const CLASS_CATCHERROR = "CLASS_CATCHERROR";
export const CLASS_RESET = "CLASS_RESET";
export const GET_SELECTED_CLASS_SUCCESS = "GET_SELECTED_CLASS_SUCCESS"
export const EDIT_SELECTED_CLASS_SUCCESS = "EDIT_SELECTED_CLASS_SUCCESS"
export const DELETED_SELECTED_CLASS_SUCCESS = "DELETED_SELECTED_CLASS_SUCCESS"

export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE"
export const SET_CLASS_PROPERTY = "SET_CLASS_PROPERTY"
export const CANCEL_EDITING_CLASS = "CANCEL_EDITING_CLASS"
// src/actions/GetClassAction.js