export const COPY_SITEMAP = "COPY_SITEMAP";
export const ON_DELETE_EDITOR = "ON_DELETE_EDITOR";
export const ON_MODAL_CLOSE = "ON_MODAL_CLOSE";
export const RESET_MODAL_STATUS = "RESET_MODAL_STATUS";

export const SET_CLIENT_MESSAGE = "SET_CLIENT_MESSAGE";
export const ON_EDITOR_STORAGE_VALUE_EXISTED = "ON_EDITOR_STORAGE_VALUE_EXISTED";