export const REQUEST_TOP_EDITOR = "REQUEST_TOP_EDITOR";
export const SEARCH_NOT_TOP_EDITOR_LIST = "SEARCH_NOT_TOP_EDITOR_LIST";
export const REQUEST_TOP_EDITOR_SUCCESS = "REQUEST_TOP_EDITOR_SUCCESS";
export const REQUEST_NOT_TOP_EDITOR_SUCCESS = "REQUEST_NOT_TOP_EDITOR_SUCCESS";
export const REQUEST_TOP_EDITOR_FAIL = "REQUEST_TOP_EDITOR_FAIL";

export const REQUEST_HOT_EDITOR = "REQUEST_HOT_EDITOR";
export const SEARCH_NOT_HOT_EDITOR_LIST = "SEARCH_NOT_HOT_EDITOR_LIST";
export const REQUEST_HOT_EDITOR_SUCCESS = "REQUEST_HOT_EDITOR_SUCCESS";
export const REQUEST_NOT_HOT_EDITOR_SUCCESS = "REQUEST_NOT_HOT_EDITOR_SUCCESS";
export const REQUEST_HOT_EDITOR_FAIL = "REQUEST_HOT_EDITOR_FAIL";

export const REQUEST_RECOMMEND_EDITOR = "REQUEST_RECOMMEND_EDITOR";
export const SEARCH_NOT_RECOMMEND_EDITOR_LIST = "SEARCH_NOT_RECOMMEND_EDITOR_LIST";
export const REQUEST_RECOMMEND_EDITOR_SUCCESS = "REQUEST_RECOMMEND_EDITOR_SUCCESS";
export const REQUEST_NOT_RECOMMEND_EDITOR_SUCCESS = "REQUEST_NOT_RECOMMEND_EDITOR_SUCCESS";
export const REQUEST_RECOMMEND_EDITOR_FAIL = "REQUEST_RECOMMEND_EDITOR_FAIL";

export const SEARCH_EDITOR_TYPE_LIST = "SEARCH_EDITOR_TYPE_LIST";

export const BUNCH_MODIFY_TYPE_LIST = "BUNCH_MODIFY_TYPE_LIST";
export const BUNCH_MODIFY_TYPE_LIST_SUCCESS = "BUNCH_MODIFY_TYPE_LIST_SUCCESS";
export const BUNCH_MODIFY_TYPE_LIST_FAIL = "BUNCH_MODIFY_TYPE_LIST_FAIL";