export const REQUEST_EDITOR = "REQUEST_EDITOR";
export const REQUEST_EDITOR_PAGE = "REQUEST_EDITOR_PAGE";
export const REQUEST_EDITOR_TITLE_LIST_SUCCESS = "REQUEST_EDITOR_TITLE_LIST_SUCCESS";
export const REQUEST_EDITOR_TITLE_LIST_FAIL = "REQUEST_EDITOR_TITLE_LIST_FAIL";
export const REQUEST_EDITOR_BY_ID = "REQUEST_EDITOR_BY_ID";
export const REQUEST_EDITOR_SUCCESS = "REQUEST_EDITOR_SUCCESS";
export const REQUEST_EDITOR_FAIL = "REQUEST_EDITOR_FAIL";

export const SEARCH_EDITOR_LIST = "SEARCH_EDITOR_LIST";
export const SHOW_EDITOR_LIST_SORTING = "SHOW_EDITOR_LIST_SORTING";
export const PAGE_BUTTON_CLICKED = "PAGE_BUTTON_CLICKED";

export const ADD_EDITOR = "ADD_EDITOR";
export const ADD_EDITOR_SUCCESS = "ADD_EDITOR_SUCCESS";
export const ADD_EDITOR_SUCCESS__NO_PAYLOAD_BACK__ = "ADD_EDITOR_SUCCESS__NO_PAYLOAD_BACK__";
export const ADD_EDITOR_FAIL = "ADD_EDITOR_FAIL";

export const UPDATE_EDITOR = "UPDATE_EDITOR";
export const UPDATE_EDITOR_SUCCESS = "UPDATE_EDITOR_SUCCESS";
export const UPDATE_EDITOR_SUCCESS__NO_PAYLOAD_BACK__ = "UPDATE_EDITOR_SUCCESS__NO_PAYLOAD_BACK__";
export const UPDATE_EDITOR_FAIL = "UPDATE_EDITOR_FAIL";

export const BUNCH_DELETE_EDITOR = "BUNCH_DELETE_EDITOR";
export const DELETE_EDITOR = "DELETE_EDITOR";
export const DELETE_EDITOR_SUCCESS = "DELETE_EDITOR_SUCCESS";
export const DELETE_EDITOR_FAIL = "DELETE_EDITOR_FAIL";

export const RESET_EDITOR = "RESET_EDITOR";
export const ADD_NEW_EDITOR = "ADD_NEW_EDITOR";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_FAIL = "AUTH_USER_FAIL";

export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";

