export const SHOW_EDITOR_URL_LIST_SORTING = 'SHOW_EDITOR_URL_LIST_SORTING'
export const SEARCH_EDITOR_URL_LIST = 'SEARCH_EDITOR_URL_LIST'
export const AUTH_USER_FAIL = 'AUTH_USER_FAIL'
export const SET_SUBSTITUTION_URL = 'SET_SUBSTITUTION_URL'

export const REQUEST_EDITOR_URL = 'REQUEST_EDITOR_URL'
export const REQUEST_EDITOR_URL_SUCCESS = 'REQUEST_EDITOR_URL_SUCCESS'
export const REQUEST_EDITOR_URL_FAIL = 'REQUEST_EDITOR_URL_FAIL'

export const CHECK_EDITOR_URL_ALL = 'CHECK_EDITOR_URL_ALL'
export const CHECK_EDITOR_URL_ALL_SUCCESS = 'CHECK_EDITOR_URL_ALL_SUCCESS'
export const CHECK_EDITOR_URL_ALL_FAIL = 'CHECK_EDITOR_URL_ALL_FAIL'

export const CHECK_EDITOR_URL = 'CHECK_EDITOR_URL'
export const CHECK_EDITOR_URL_SUCCESS = 'CHECK_EDITOR_URL_SUCCESS'
export const CHECK_EDITOR_URL_FAIL = 'CHECK_EDITOR_URL_FAIL'

export const EDITING_URL = 'EDITING_URL'
export const CANCEL_EDITING_URL = 'CANCEL_EDITING_URL'
export const UPDATE_EDITOR_URL = 'UPDATE_EDITOR_URL'
export const UPDATE_EDITOR_URL_SUCCESS = 'UPDATE_EDITOR_URL_SUCCESS'
export const UPDATE_EDITOR_URL_FAIL = 'UPDATE_EDITOR_URL_FAIL'

export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";