export const SET_DEFAULT_FORM_VALUE = "SET_DEFAULT_FORM_VALUE";
export const RESET_FORM_VALUE = "RESET_FORM_VALUE";
export const SET_PROPERTY = "SET_PROPERTY";
export const SET_SHOW_URL = "SET_SHOW_URL";
export const CHECK_BEFORE_SUBMIT = "CHECK_BEFORE_SUBMIT";

export const PREVIEW_EDITOR = "PREVIEW_EDITOR";
export const PREVIEW_EDITOR_SUCCESS = "PREVIEW_EDITOR_SUCCESS";
export const PREVIEW_EDITOR_FAIL = "PREVIEW_EDITOR_FAIL";