export const LOGGER_REQUEST = "LOGGER_REQUEST";
export const LOGGER_SUCCESS = "LOGGER_SUCCESS";
export const LOGGER_RESPONSE = "LOGGER_RESPONSE";
export const LOGGER_FAIL = "LOGGER_FAIL";
export const LOGGER_CATCHERROR = "LOGGER_CATCHERROR";
export const LOGGER_RESET = "LOGGER_RESET";
